- name: Install MongoDb | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

- name: Install MongoDb | Add 10Gen repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: Install MongoDb | Install latest MongoDB release 
  apt: pkg=mongodb-org state=present update_cache=yes

- name: Install MongoDb | Insure deamon is running correctly
  service: name=mongod state=started