- name: Install openjdk-7-jdk
  apt: name=openjdk-7-jdk update_cache=yes

- name: Install tomcat7
  apt: name=tomcat7 update_cache=no

- name: Install git
  apt: name=git update_cache=no

- name: Install sed
  apt: name=sed update_cache=no

- name: Install unzip
  apt: name=unzip update_cache=no

- name: Install curl
  apt: name=curl update_cache=no